name: EasyBetterChat
version: 1.0
main: me.ThijsHFT.EasyBetterChat.Main
description: Plugin to allow prefix based chat formatting without EssentialsChat.
author: ThijsHFT
depend: [Vault]
commands:
    ebcreload:
      description: Reloads configuration files
      aliases: [ebcrefresh, ebcr]
      permission: ebc.reload
permissions:
    ebc.*:
        description: ability to use all commands
        children:
            ebc.reload: true
    ebc.reload:
        description: ability to use the reload command