name: PrefChat
version: 1.1
main: me.ThijsHFT.PrefChat.Main
description: Plugin to allow prefix based chat formatting without EssentialsChat.
author: ThijsHFT
depend: [Vault]
commands:
    pfcreload:
      description: Reloads configuration files
      aliases: [pfcrefresh, pfcr]
      permission: prefchat.reload
permissions:
    prefchat.*:
        description: ability to use all commands
        children:
            prefchat.reload: true
    prefchat.reload:
        description: ability to use the reload command